# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'course_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ourse_service.proto\x12\rcourseservice\"_\n\x13\x43reateCourseRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tmax_score\x18\x03 \x01(\x05\x12\x11\n\tmin_score\x18\x04 \x01(\x05\"%\n\x10GetCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"(\n\x13\x44\x65leteCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"m\n\x0e\x43ourseResponse\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tmax_score\x18\x04 \x01(\x05\x12\x11\n\tmin_score\x18\x05 \x01(\x05\"\'\n\x14\x44\x65leteCourseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8e\x02\n\rCourseService\x12S\n\x0c\x43reateCourse\x12\".courseservice.CreateCourseRequest\x1a\x1d.courseservice.CourseResponse\"\x00\x12M\n\tGetCourse\x12\x1f.courseservice.GetCourseRequest\x1a\x1d.courseservice.CourseResponse\"\x00\x12Y\n\x0c\x44\x65leteCourse\x12\".courseservice.DeleteCourseRequest\x1a#.courseservice.DeleteCourseResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOURSEREQUEST']._serialized_start=39
  _globals['_CREATECOURSEREQUEST']._serialized_end=134
  _globals['_GETCOURSEREQUEST']._serialized_start=136
  _globals['_GETCOURSEREQUEST']._serialized_end=173
  _globals['_DELETECOURSEREQUEST']._serialized_start=175
  _globals['_DELETECOURSEREQUEST']._serialized_end=215
  _globals['_COURSERESPONSE']._serialized_start=217
  _globals['_COURSERESPONSE']._serialized_end=326
  _globals['_DELETECOURSERESPONSE']._serialized_start=328
  _globals['_DELETECOURSERESPONSE']._serialized_end=367
  _globals['_COURSESERVICE']._serialized_start=370
  _globals['_COURSESERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
